export const TOGGLE_IS_AUTHENTICATED = `SET_IS_AUTHENTICATED`;
export const REGISTER_SUCCESS = `REGISTER_SUCCESS`;
export const REGISTER_FAILURE = `REGISTER_FAILURE`;
export const SET_ALERT = `SET_ALERT`;
export const CLEAR_ALERT = `CLEAR_ALERT`;
